# Generated by Django 3.1 on 2020-08-17 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivo',
            name='tiempo_cosecha',
            field=models.IntegerField(default=1, verbose_name='Tiempo estimado de cosecha'),
            preserve_default=False,
        ),
    ]
